# Generated by Django 4.1.2 on 2024-06-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='site_renkleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renkbir', models.CharField(max_length=10, verbose_name='Renk Bir')),
                ('renkiki', models.CharField(max_length=10, verbose_name='Renk İki')),
                ('renkuc', models.CharField(max_length=10, verbose_name='Renk Üç')),
                ('renkdort', models.CharField(max_length=10, verbose_name='Renk Dört')),
            ],
        ),
        migrations.AlterModelOptions(
            name='adres',
            options={'verbose_name': 'Şirket Adresi Yazı Olarak', 'verbose_name_plural': 'Şirket Adresi Yazı Olarak'},
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Şirket Banner Ayarı', 'verbose_name_plural': 'Şirket Banner Ayarı'},
        ),
        migrations.AlterModelOptions(
            name='email_adres',
            options={'verbose_name': 'Şirket Email Adresi ', 'verbose_name_plural': 'Şirket Email Adresi'},
        ),
        migrations.AlterModelOptions(
            name='gomulu_adres',
            options={'verbose_name': 'Şirket Adresi Harita Gömme', 'verbose_name_plural': 'Şirket Adresi Harita Gömme'},
        ),
        migrations.AlterModelOptions(
            name='hakkimizda',
            options={'verbose_name': 'Şirket Hakkımızda Yazısı', 'verbose_name_plural': 'Şirket Hakkımızda Yazısı'},
        ),
        migrations.AlterModelOptions(
            name='numara',
            options={'verbose_name': 'Şirket Numarası', 'verbose_name_plural': 'Şirket Numaraları'},
        ),
        migrations.AlterModelOptions(
            name='sayfa_iconu',
            options={'verbose_name': 'Sayfa İconu', 'verbose_name_plural': 'Sayfa İconları'},
        ),
        migrations.AlterModelOptions(
            name='sayfa_logosu',
            options={'verbose_name': 'Sayfa Logosu', 'verbose_name_plural': 'Sayfa Logoları'},
        ),
        migrations.AlterModelOptions(
            name='seo_ayarlari',
            options={'verbose_name': 'Şirket Seo Ayarı', 'verbose_name_plural': 'Şirket Seo Ayarı'},
        ),
        migrations.AlterModelOptions(
            name='site_adi',
            options={'verbose_name': 'Sayfa Adı', 'verbose_name_plural': 'Sayfa Adları'},
        ),
        migrations.AlterModelOptions(
            name='sosyalmedyaface',
            options={'verbose_name': 'Şirket Facebook Adresi ', 'verbose_name_plural': 'Facebook Linkedin Adresi'},
        ),
        migrations.AlterModelOptions(
            name='sosyalmedyainsgr',
            options={'verbose_name': 'Şirket İnstagram Adresi ', 'verbose_name_plural': 'Şirket İnstagram Adresi'},
        ),
        migrations.AlterModelOptions(
            name='sosyalmedyalinkd',
            options={'verbose_name': 'Şirket Linkedin Adresi ', 'verbose_name_plural': 'Şirket Linkedin Adresi'},
        ),
        migrations.AlterModelOptions(
            name='sosyalmedyatw',
            options={'verbose_name': 'Şirket Twitter Adresi ', 'verbose_name_plural': 'Facebook Twitter Adresi'},
        ),
        migrations.AlterModelOptions(
            name='sosyalmedyayoutube',
            options={'verbose_name': 'Şirket Youtube Adresi ', 'verbose_name_plural': 'Facebook Youtube Adresi'},
        ),
    ]
