# Generated by Django 4.1.2 on 2024-06-01 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_site_renkleri_alter_adres_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site_renkleri',
            options={'verbose_name': 'Sayfa Renkleri', 'verbose_name_plural': 'Sayfa Renkleri'},
        ),
    ]
