# Generated by Django 4.2.13 on 2024-07-05 00:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_alter_site_renkleri_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='spor_okulu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hakkimizda_tr', ckeditor.fields.RichTextField(verbose_name='Anasayfa Yazısı Türkçe')),
            ],
        ),
    ]
