# Generated by Django 4.1.2 on 2024-03-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='u_11_takimi_son_karsilasma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ev_sahibi_takim_adi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ev SAhibi Takım')),
                ('ev_sahibi_takim_logusu', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ev SAhibi Takım Logusu Link')),
                ('ev_sahibi_kazanma_kaybetme', models.CharField(choices=[('', ''), ('MAĞLUP', 'MAĞLUP'), ('KAZANAN', 'KAZANAN')], default='', max_length=200)),
                ('ev_sahibi_skoru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ev SAhibi Skoru')),
                ('ev_sahibi_gol_atanlar', models.TextField(blank=True, null=True, verbose_name='Ev Sahibi Gol Atanlar')),
                ('karsilasma_tarihi', models.TextField(blank=True, null=True, verbose_name='Karşılaşma Tarihi')),
                ('karsilasma_yeri', models.TextField(blank=True, null=True, verbose_name='Karşılaşma yeri')),
                ('deplasman_takim_adi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Deplasman Takım')),
                ('deplasman_takim_logusu', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Deplasman Takım Logusu Link')),
                ('deplasman_kazanma_kaybetme', models.CharField(choices=[('', ''), ('MAĞLUP', 'MAĞLUP'), ('KAZANAN', 'KAZANAN')], default='', max_length=200)),
                ('deplasman_skoru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Deplasman Skoru')),
                ('deplasman_gol_atanlar', models.TextField(blank=True, null=True, verbose_name='Deplasman Gol Atanlar')),
            ],
        ),
        migrations.CreateModel(
            name='u_12_takimi_son_karsilasma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ev_sahibi_takim_adi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ev SAhibi Takım')),
                ('ev_sahibi_takim_logusu', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ev SAhibi Takım Logusu Link')),
                ('ev_sahibi_kazanma_kaybetme', models.CharField(choices=[('', ''), ('MAĞLUP', 'MAĞLUP'), ('KAZANAN', 'KAZANAN')], default='', max_length=200)),
                ('ev_sahibi_skoru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ev SAhibi Skoru')),
                ('ev_sahibi_gol_atanlar', models.TextField(blank=True, null=True, verbose_name='Ev Sahibi Gol Atanlar')),
                ('karsilasma_tarihi', models.TextField(blank=True, null=True, verbose_name='Karşılaşma Tarihi')),
                ('karsilasma_yeri', models.TextField(blank=True, null=True, verbose_name='Karşılaşma yeri')),
                ('deplasman_takim_adi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Deplasman Takım')),
                ('deplasman_takim_logusu', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Deplasman Takım Logusu Link')),
                ('deplasman_kazanma_kaybetme', models.CharField(choices=[('', ''), ('MAĞLUP', 'MAĞLUP'), ('KAZANAN', 'KAZANAN')], default='', max_length=200)),
                ('deplasman_skoru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Deplasman Skoru')),
                ('deplasman_gol_atanlar', models.TextField(blank=True, null=True, verbose_name='Deplasman Gol Atanlar')),
            ],
        ),
        migrations.CreateModel(
            name='u_13_takimi_son_karsilasma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ev_sahibi_takim_adi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ev SAhibi Takım')),
                ('ev_sahibi_takim_logusu', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ev SAhibi Takım Logusu Link')),
                ('ev_sahibi_kazanma_kaybetme', models.CharField(choices=[('', ''), ('MAĞLUP', 'MAĞLUP'), ('KAZANAN', 'KAZANAN')], default='', max_length=200)),
                ('ev_sahibi_skoru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ev SAhibi Skoru')),
                ('ev_sahibi_gol_atanlar', models.TextField(blank=True, null=True, verbose_name='Ev Sahibi Gol Atanlar')),
                ('karsilasma_tarihi', models.TextField(blank=True, null=True, verbose_name='Karşılaşma Tarihi')),
                ('karsilasma_yeri', models.TextField(blank=True, null=True, verbose_name='Karşılaşma yeri')),
                ('deplasman_takim_adi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Deplasman Takım')),
                ('deplasman_takim_logusu', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Deplasman Takım Logusu Link')),
                ('deplasman_kazanma_kaybetme', models.CharField(choices=[('', ''), ('MAĞLUP', 'MAĞLUP'), ('KAZANAN', 'KAZANAN')], default='', max_length=200)),
                ('deplasman_skoru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Deplasman Skoru')),
                ('deplasman_gol_atanlar', models.TextField(blank=True, null=True, verbose_name='Deplasman Gol Atanlar')),
            ],
        ),
    ]
