# Generated by Django 4.1.2 on 2024-03-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='u_11_takimi_son_karsilasma',
            name='deplasman_kazanma_kaybetme',
            field=models.CharField(blank=True, choices=[('', ''), ('MAĞLUP', 'MAĞLUP'), ('KAZANAN', 'KAZANAN')], default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='u_11_takimi_son_karsilasma',
            name='ev_sahibi_kazanma_kaybetme',
            field=models.CharField(blank=True, choices=[('', ''), ('MAĞLUP', 'MAĞLUP'), ('KAZANAN', 'KAZANAN')], default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='u_12_takimi_son_karsilasma',
            name='deplasman_kazanma_kaybetme',
            field=models.CharField(blank=True, choices=[('', ''), ('MAĞLUP', 'MAĞLUP'), ('KAZANAN', 'KAZANAN')], default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='u_12_takimi_son_karsilasma',
            name='ev_sahibi_kazanma_kaybetme',
            field=models.CharField(blank=True, choices=[('', ''), ('MAĞLUP', 'MAĞLUP'), ('KAZANAN', 'KAZANAN')], default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='u_13_takimi_son_karsilasma',
            name='deplasman_kazanma_kaybetme',
            field=models.CharField(blank=True, choices=[('', ''), ('MAĞLUP', 'MAĞLUP'), ('KAZANAN', 'KAZANAN')], default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='u_13_takimi_son_karsilasma',
            name='ev_sahibi_kazanma_kaybetme',
            field=models.CharField(blank=True, choices=[('', ''), ('MAĞLUP', 'MAĞLUP'), ('KAZANAN', 'KAZANAN')], default='', max_length=200, null=True),
        ),
    ]
