# Generated by Django 4.1.2 on 2024-03-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0002_alter_u_11_takimi_son_karsilasma_deplasman_kazanma_kaybetme_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='u_11_skor_sayfasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_bilgisi', models.CharField(max_length=400, verbose_name='u - 11 tff sayfa linki')),
            ],
        ),
        migrations.CreateModel(
            name='u_12_skor_sayfasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_bilgisi', models.CharField(max_length=400, verbose_name='u - 12 tff sayfa linki')),
            ],
        ),
        migrations.CreateModel(
            name='u_13_skor_sayfasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_bilgisi', models.CharField(max_length=400, verbose_name='u - 13 tff sayfa linki')),
            ],
        ),
    ]
