# Generated by Django 4.1.2 on 2024-04-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0004_teknik_kadro_ekibi'),
    ]

    operations = [
        migrations.AddField(
            model_name='teknik_kadro_ekibi',
            name='gorevi',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Görevi'),
        ),
    ]
