# Generated by Django 4.1.2 on 2024-04-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0005_teknik_kadro_ekibi_gorevi'),
    ]

    operations = [
        migrations.CreateModel(
            name='formalarimiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(blank=True, max_length=200, null=True, verbose_name='Baslik')),
                ('aciklamasi', models.TextField(blank=True, verbose_name='Formalarımız')),
                ('fotografi', models.ImageField(upload_to='formalarimiz/', verbose_name='Formalarımız')),
            ],
        ),
    ]
