# Generated by Django 4.1.2 on 2024-04-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0006_formalarimiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='u_11_fotograflari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(blank=True, max_length=200, null=True, verbose_name='Baslik')),
                ('aciklamasi', models.TextField(blank=True, verbose_name='Formalarımız')),
                ('fotografi', models.ImageField(upload_to='u_11/', verbose_name='Formalarımız')),
            ],
        ),
        migrations.CreateModel(
            name='u_12_fotograflari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(blank=True, max_length=200, null=True, verbose_name='Baslik')),
                ('aciklamasi', models.TextField(blank=True, verbose_name='Formalarımız')),
                ('fotografi', models.ImageField(upload_to='u_12/', verbose_name='Formalarımız')),
            ],
        ),
        migrations.CreateModel(
            name='u_13_fotograflari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(blank=True, max_length=200, null=True, verbose_name='Baslik')),
                ('aciklamasi', models.TextField(blank=True, verbose_name='Formalarımız')),
                ('fotografi', models.ImageField(upload_to='u_13/', verbose_name='Formalarımız')),
            ],
        ),
    ]
