# Generated by Django 4.1.2 on 2024-04-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0007_u_11_fotograflari_u_12_fotograflari_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='u_11_oyunculari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi_soyadi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Adı Soyadı')),
                ('forma_numarasi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Forma Numarası')),
                ('boyu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Boyu')),
                ('kilosu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kilosu')),
                ('dogum_tarihi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Doğum Tarihi')),
                ('hobisi', models.TextField(blank=True, verbose_name='hobisi')),
                ('aciklamasi', models.TextField(blank=True, verbose_name='Formalarımız')),
                ('fotografi', models.ImageField(upload_to='oyunculari/', verbose_name='Formalarımız')),
            ],
        ),
        migrations.CreateModel(
            name='u_12_oyunculari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi_soyadi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Adı Soyadı')),
                ('forma_numarasi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Forma Numarası')),
                ('boyu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Boyu')),
                ('kilosu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kilosu')),
                ('dogum_tarihi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Doğum Tarihi')),
                ('hobisi', models.TextField(blank=True, verbose_name='hobisi')),
                ('aciklamasi', models.TextField(blank=True, verbose_name='Formalarımız')),
                ('fotografi', models.ImageField(upload_to='oyunculari/', verbose_name='Formalarımız')),
            ],
        ),
        migrations.CreateModel(
            name='u_13_oyunculari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi_soyadi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Adı Soyadı')),
                ('forma_numarasi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Forma Numarası')),
                ('boyu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Boyu')),
                ('kilosu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kilosu')),
                ('dogum_tarihi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Doğum Tarihi')),
                ('hobisi', models.TextField(blank=True, verbose_name='hobisi')),
                ('aciklamasi', models.TextField(blank=True, verbose_name='Formalarımız')),
                ('fotografi', models.ImageField(upload_to='oyunculari/', verbose_name='Formalarımız')),
            ],
        ),
    ]
