# Generated by Django 4.2.13 on 2024-07-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0010_alter_formalarimiz_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sponsorlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi_soyadi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sponsor Adı')),
                ('fotografi', models.ImageField(upload_to='oyunculari/', verbose_name='Formalarımız')),
            ],
            options={
                'verbose_name': 'Sponsorlarımız',
                'verbose_name_plural': 'Sponsorlarımız',
            },
        ),
    ]
