# Generated by Django 4.2.13 on 2024-08-08 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0013_kupalarimiz_yonetim_klubu_ekibi'),
    ]

    operations = [
        migrations.CreateModel(
            name='u_14_fotograflari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(blank=True, max_length=200, null=True, verbose_name='Baslik')),
                ('aciklamasi', models.TextField(blank=True, verbose_name='Açıklama')),
                ('fotografi', models.ImageField(upload_to='u_12/', verbose_name='Formalarımız')),
            ],
            options={
                'verbose_name': 'U-14 Fotoğraflarımız',
                'verbose_name_plural': 'U-14 Fotoğraflarımız',
            },
        ),
        migrations.CreateModel(
            name='u_14_oyunculari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi_soyadi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Adı Soyadı')),
                ('forma_numarasi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Forma Numarası')),
                ('boyu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Boyu')),
                ('kilosu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kilosu')),
                ('dogum_tarihi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Doğum Tarihi')),
                ('mevki', models.CharField(blank=True, max_length=200, verbose_name='mevki')),
                ('hobisi', models.TextField(blank=True, verbose_name='hobisi')),
                ('aciklamasi', models.TextField(blank=True, verbose_name='Formalarımız')),
                ('fotografi', models.ImageField(upload_to='oyunculari/', verbose_name='Formalarımız')),
            ],
            options={
                'verbose_name': 'U-14 Oyuncularımız',
                'verbose_name_plural': 'U-14 Oyuncularımız',
            },
        ),
        migrations.CreateModel(
            name='u_14_skor_sayfasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_bilgisi', models.CharField(max_length=400, verbose_name='u - 13 tff sayfa linki')),
            ],
            options={
                'verbose_name': 'U-14 TFF Bilgi Sayfası',
                'verbose_name_plural': 'U-14 TFF Bilgi Sayfası',
            },
        ),
        migrations.CreateModel(
            name='u_14_takimi_son_karsilasma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ev_sahibi_takim_adi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ev SAhibi Takım')),
                ('ev_sahibi_takim_logusu', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ev SAhibi Takım Logusu Link')),
                ('ev_sahibi_kazanma_kaybetme', models.CharField(blank=True, choices=[('', ''), ('MAĞLUP', 'MAĞLUP'), ('KAZANAN', 'KAZANAN')], default='', max_length=200, null=True)),
                ('ev_sahibi_skoru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ev SAhibi Skoru')),
                ('ev_sahibi_gol_atanlar', models.TextField(blank=True, null=True, verbose_name='Ev Sahibi Gol Atanlar')),
                ('karsilasma_tarihi', models.TextField(blank=True, null=True, verbose_name='Karşılaşma Tarihi')),
                ('karsilasma_yeri', models.TextField(blank=True, null=True, verbose_name='Karşılaşma yeri')),
                ('deplasman_takim_adi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Deplasman Takım')),
                ('deplasman_takim_logusu', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Deplasman Takım Logusu Link')),
                ('deplasman_kazanma_kaybetme', models.CharField(blank=True, choices=[('', ''), ('MAĞLUP', 'MAĞLUP'), ('KAZANAN', 'KAZANAN')], default='', max_length=200, null=True)),
                ('deplasman_skoru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Deplasman Skoru')),
                ('deplasman_gol_atanlar', models.TextField(blank=True, null=True, verbose_name='Deplasman Gol Atanlar')),
            ],
            options={
                'verbose_name': 'U-14 Takım Son Karşılaşması',
                'verbose_name_plural': 'U-14 Takım Son Karşılaşması',
            },
        ),
        migrations.CreateModel(
            name='u_15_fotograflari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(blank=True, max_length=200, null=True, verbose_name='Baslik')),
                ('aciklamasi', models.TextField(blank=True, verbose_name='Açıklma')),
                ('fotografi', models.ImageField(upload_to='u_13/', verbose_name='Formalarımız')),
            ],
            options={
                'verbose_name': 'U-15 Fotoğraflarımız',
                'verbose_name_plural': 'U-15 Fotoğraflarımız',
            },
        ),
        migrations.CreateModel(
            name='u_15_oyunculari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi_soyadi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Adı Soyadı')),
                ('forma_numarasi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Forma Numarası')),
                ('boyu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Boyu')),
                ('kilosu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kilosu')),
                ('dogum_tarihi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Doğum Tarihi')),
                ('mevki', models.CharField(blank=True, max_length=200, verbose_name='mevki')),
                ('hobisi', models.TextField(blank=True, verbose_name='hobisi')),
                ('aciklamasi', models.TextField(blank=True, verbose_name='Formalarımız')),
                ('fotografi', models.ImageField(upload_to='oyunculari/', verbose_name='Formalarımız')),
            ],
            options={
                'verbose_name': 'U-15 Oyuncularımız',
                'verbose_name_plural': 'U-15 Oyuncularımız',
            },
        ),
        migrations.CreateModel(
            name='u_15_skor_sayfasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_bilgisi', models.CharField(max_length=400, verbose_name='u - 13 tff sayfa linki')),
            ],
            options={
                'verbose_name': 'U-15 TFF Bilgi Sayfası',
                'verbose_name_plural': 'U-15 TFF Bilgi Sayfası',
            },
        ),
        migrations.CreateModel(
            name='u_15_takimi_son_karsilasma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ev_sahibi_takim_adi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ev SAhibi Takım')),
                ('ev_sahibi_takim_logusu', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ev SAhibi Takım Logusu Link')),
                ('ev_sahibi_kazanma_kaybetme', models.CharField(blank=True, choices=[('', ''), ('MAĞLUP', 'MAĞLUP'), ('KAZANAN', 'KAZANAN')], default='', max_length=200, null=True)),
                ('ev_sahibi_skoru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ev SAhibi Skoru')),
                ('ev_sahibi_gol_atanlar', models.TextField(blank=True, null=True, verbose_name='Ev Sahibi Gol Atanlar')),
                ('karsilasma_tarihi', models.TextField(blank=True, null=True, verbose_name='Karşılaşma Tarihi')),
                ('karsilasma_yeri', models.TextField(blank=True, null=True, verbose_name='Karşılaşma yeri')),
                ('deplasman_takim_adi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Deplasman Takım')),
                ('deplasman_takim_logusu', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Deplasman Takım Logusu Link')),
                ('deplasman_kazanma_kaybetme', models.CharField(blank=True, choices=[('', ''), ('MAĞLUP', 'MAĞLUP'), ('KAZANAN', 'KAZANAN')], default='', max_length=200, null=True)),
                ('deplasman_skoru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Deplasman Skoru')),
                ('deplasman_gol_atanlar', models.TextField(blank=True, null=True, verbose_name='Deplasman Gol Atanlar')),
            ],
            options={
                'verbose_name': 'U-15 Takım Son Karşılaşması',
                'verbose_name_plural': 'U-15 Takım Son Karşılaşması',
            },
        ),
    ]
