# Generated by Django 4.2.13 on 2024-08-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0014_u_14_fotograflari_u_14_oyunculari_u_14_skor_sayfasi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='deactive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deactive_active', models.BooleanField()),
            ],
        ),
    ]
